apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: sbr-ns
spec:
  releaseName: nginx-dev
  chart:
    spec:
      chart: helm-nginx-chart
      sourceRef:
        kind: GitRepository
        name: helm-nginx-chart
  interval: 10m
  replicas: 2


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-2
  namespace: sbr-ns
spec:
  releaseName: nginx-sys
  chart:
    spec:
      chart: helm-nginx-chart
      sourceRef:
        kind: GitRepository
        name: helm-nginx-chart
  interval: 10m
  replicas: 1
