apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-dep
  namespace: sbr-ns
spec:
  releaseName: nginx-uat
  chart:
    spec:
      chart: helm-nginx-chart
      sourceRef:
        kind: GitRepository
        name: helm-nginx-chart
  interval: 5m
  values:
    replicaCount: 1
